server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlyForKoreans?serverTimezone=Asia/Seoul
    username: root
    password: asdf1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect

jackson:
  serialization:
    fail-on-empty-beans=false: false